// Sandburg helper installers and shell wrapper generation
import { createGrepToolDefinition, getAgentDir } from "@mariozechner/pi-coding-agent";
import { spawnSync } from "child_process";
import {
	chmodSync,
	existsSync,
	mkdirSync,
	readFileSync,
	realpathSync,
	renameSync,
	rmSync,
	statSync,
	writeFileSync,
} from "fs";
import { basename, dirname, isAbsolute, join, resolve } from "path";

export const ACTIVE_MARKER = "sandburg-extension-v1";
const RG_PROBE_MESSAGE = "sandburg-rg-wrapper-probe-hit";
export const TOOL_SANDBOX_RUNNER_MARKER = "# sandburg-extension-managed: tool-sandbox-runner v1";
export const RG_MARKER = "# sandburg-extension-managed: rg-wrapper v1";
export const AGENT_DIR = resolve(getAgentDir());
export const AGENT_BIN_DIR = join(AGENT_DIR, "bin");
export const AUTH_JSON_PATH = join(AGENT_DIR, "auth.json");
export const TOOL_SANDBOX_RUNNER_PATH = join(AGENT_BIN_DIR, "sandburg-tool-sandbox");
export const RG_WRAPPER_PATH = join(AGENT_BIN_DIR, "rg");
export const JITI_CACHE_DIR = "/tmp/jiti";
const extraRoPathsValue = process.env.SANDBURG_RO_PATHS ?? "";
export const EXTRA_RO_PATHS = extraRoPathsValue === "" ? [] : extraRoPathsValue.split(":");

const TOOL_SANDBOX_RUNNER_SCRIPT = `#!/usr/bin/env bash
${TOOL_SANDBOX_RUNNER_MARKER}
#
# Generated by the Sandburg Pi extension. Safe to remove when Pi is not using it;
# the extension recreates it on startup. Do not edit in place: if customization is
# needed, change the extension that generated this file.

set -euo pipefail

if (($# == 0)); then
    echo "Usage: sandburg-tool-sandbox COMMAND [ARG...]" >&2
    exit 2
fi

: "\${HOME:?sandburg-tool-sandbox: HOME is not set}"
: "\${USER:?sandburg-tool-sandbox: USER is not set}"
: "\${PATH:?sandburg-tool-sandbox: PATH is not set}"
: "\${SANDBURG_ACTIVE:?sandburg-tool-sandbox: SANDBURG_ACTIVE is not set}"
: "\${SANDBURG_AGENT_DIR:?sandburg-tool-sandbox: SANDBURG_AGENT_DIR is not set}"
: "\${SANDBURG_AUTH_PATH:?sandburg-tool-sandbox: SANDBURG_AUTH_PATH is not set}"

home=$HOME
user=$USER
logname=\${LOGNAME:-$user}
sandbox_path=$PATH
agent_dir=$SANDBURG_AGENT_DIR
auth_path=$SANDBURG_AUTH_PATH
extra_ro_paths=\${SANDBURG_RO_PATHS:-}
term=\${TERM:-xterm-256color}
lang=\${LANG:-C.UTF-8}

if [[ ! -d $agent_dir ]]; then
    echo "sandburg-tool-sandbox: Pi agent directory not found: $agent_dir" >&2
    exit 2
fi

bwrap_args=(
    --unshare-all
    --die-with-parent
    --new-session
    --bind / /
    --dev /dev
    --proc /proc
    --ro-bind "$agent_dir" "$agent_dir"
)

# Extra read-only paths are supplied by trusted launch configuration as a
# colon-separated list. Each path is rebound read-only so agent-facing
# subprocesses cannot mutate protected Pi state through explicit backing-store
# aliases. bwrap fails closed if a configured path is missing; invalid entries
# are rejected by the extension's tool contract before agent tools run.
IFS=: read -r -a extra_ro_path_array <<< "$extra_ro_paths"
for path in "\${extra_ro_path_array[@]}"; do
    bwrap_args+=(--ro-bind "$path" "$path")
done

env_args=(
    --clearenv
    --setenv HOME "$home"
    --setenv USER "$user"
    --setenv LOGNAME "$logname"
    --setenv SHELL /bin/sh
    --setenv PATH "$sandbox_path"
    --setenv TERM "$term"
    --setenv LANG "$lang"
    --setenv SANDBURG_ACTIVE "$SANDBURG_ACTIVE"
    --setenv SANDBURG_TOOL_SANDBOX 1
    --setenv SANDBURG_AGENT_DIR "$agent_dir"
    --setenv SANDBURG_AUTH_PATH "$auth_path"
)

if [[ -n \${COLORTERM:-} ]]; then
    env_args+=(--setenv COLORTERM "$COLORTERM")
fi

for name in "\${!LC_@}"; do
    env_args+=(--setenv "$name" "\${!name}")
done

if [[ -n $extra_ro_paths ]]; then
    env_args+=(--setenv SANDBURG_RO_PATHS "$extra_ro_paths")
fi

# Mount an empty regular file over auth.json. --ro-bind-data takes an fd, so fd
# 9 is opened from /dev/null at the end of this command.
exec bwrap \
    "\${bwrap_args[@]}" \
    --ro-bind-data 9 "$auth_path" \
    --tmpfs /tmp/jiti \
    "\${env_args[@]}" \
    "$@" 9</dev/null
`;

export function shQuote(value: string): string {
	return `'${value.replace(/'/g, `'\\''`)}'`;
}

function rgWrapperScript(realRgPath: string, toolSandboxRunnerPath: string): string {
	return `#!/bin/sh
${RG_MARKER}
#
# Generated by the Sandburg Pi extension. Safe to remove when Pi is not using it;
# the extension recreates it on startup. Do not edit in place: if customization is
# needed, change the extension that generated this file.

set -eu

active_marker=${shQuote(ACTIVE_MARKER)}
probe_message=${shQuote(RG_PROBE_MESSAGE)}
real_rg=${shQuote(realRgPath)}
tool_sandbox_runner=${shQuote(toolSandboxRunnerPath)}

# Startup self-test hook used by the extension to verify that Pi's grep tool
# reaches this wrapper. This intentionally writes only to stderr and exits
# before entering the sandbox or touching the filesystem.
if [ "\${SANDBURG_RG_WRAPPER_PROBE:-}" = "$active_marker" ]; then
    echo "$probe_message" >&2
    exit 86
fi

if [ "\${SANDBURG_ACTIVE:-}" != "$active_marker" ] || [ "\${SANDBURG_TOOL_SANDBOX:-}" = 1 ]; then
    exec "$real_rg" "$@"
fi

exec "$tool_sandbox_runner" "$real_rg" "$@"
`;
}

function fatal(message: string): never {
	throw new Error(
		[
			"Sandburg Pi extension cannot start.",
			message,
			"",
			"Refusing to run without sandbox helpers installed safely.",
			"Inspect the path above. If it is safe to replace, move it aside or delete it, then restart Pi.",
			"If it is an older manually installed Sandburg Pi helper, remove it; this extension will recreate it.",
		].join("\n"),
	);
}

export function isManagedFile(path: string, marker: string): boolean {
	try {
		return readFileSync(path, "utf-8").includes(marker);
	} catch {
		return false;
	}
}

function isExecutable(path: string): boolean {
	try {
		return (statSync(path).mode & 0o111) !== 0;
	} catch {
		return false;
	}
}

function isScriptFile(path: string): boolean {
	try {
		const real = realpathSync(path);
		const bytes = readFileSync(real).subarray(0, 2).toString("utf-8");
		return bytes === "#!";
	} catch {
		return false;
	}
}

function isRipgrep(path: string): boolean {
	if (!isExecutable(path)) return false;
	const result = spawnSync(path, ["--version"], {
		encoding: "utf-8",
		stdio: ["ignore", "pipe", "ignore"],
		timeout: 3000,
	});
	return result.status === 0 && result.stdout.startsWith("ripgrep ");
}

function isPlainRipgrep(path: string): boolean {
	return !isScriptFile(path) && isRipgrep(path);
}

function writeExecutable(path: string, content: string) {
	const tempPath = join(dirname(path), `.${basename(path)}.${process.pid}.${Date.now()}.${Math.random().toString(36).slice(2)}.tmp`);
	try {
		writeFileSync(tempPath, content, { encoding: "utf-8", mode: 0o755, flag: "wx" });
		chmodSync(tempPath, 0o755);
		renameSync(tempPath, path);
	} catch (error) {
		rmSync(tempPath, { force: true });
		throw error;
	}
}

function installManagedExecutable(path: string, content: string, marker: string, label: string) {
	if (existsSync(path) && !isManagedFile(path, marker)) {
		fatal(
			[
				`Refusing to replace existing ${label}:`,
				"",
				`  ${path}`,
				"",
				"The file is not managed by this extension.",
			].join("\n"),
		);
	}

	if (!existsSync(path) || readFileSync(path, "utf-8") !== content) {
		writeExecutable(path, content);
	}
	chmodSync(path, 0o755);
}

function pathEntries(pathValue: string): string[] {
	return pathValue.split(":").filter(Boolean);
}

function sameExistingPath(a: string, b: string): boolean {
	try {
		return realpathSync(a) === realpathSync(b);
	} catch {
		return resolve(a) === resolve(b);
	}
}

function findRealRgOnPathSkipping(binDir: string): string | undefined {
	for (const dir of pathEntries(process.env.PATH ?? "")) {
		if (!isAbsolute(dir)) continue;
		const candidateDir = resolve(dir);
		if (sameExistingPath(candidateDir, binDir)) continue;

		const candidate = join(candidateDir, "rg");
		if (existsSync(candidate) && isPlainRipgrep(candidate)) {
			return realpathSync(candidate);
		}
	}
	return undefined;
}

// Resolve the real ripgrep that the persistent wrapper will delegate to. PATH
// fallback deliberately skips getAgentDir()/bin and relative entries so the
// wrapper cannot delegate to itself.
function resolveRealRg(): string {
	const realRg = findRealRgOnPathSkipping(AGENT_BIN_DIR);
	if (!realRg) {
		fatal(
			[
				"No real ripgrep binary was found.",
				"",
				`This extension needs real rg so it can install ${RG_WRAPPER_PATH} as a sandbox wrapper.`,
				`Install ripgrep or ensure rg is available outside ${AGENT_BIN_DIR}, then restart Pi.`,
			].join("\n"),
		);
	}

	return realRg;
}

export function installSandburgHelpers() {
	mkdirSync(AGENT_BIN_DIR, { recursive: true });
	installManagedExecutable(
		TOOL_SANDBOX_RUNNER_PATH,
		TOOL_SANDBOX_RUNNER_SCRIPT,
		TOOL_SANDBOX_RUNNER_MARKER,
		"tool sandbox runner",
	);

	const realRg = resolveRealRg();
	installManagedExecutable(RG_WRAPPER_PATH, rgWrapperScript(realRg, TOOL_SANDBOX_RUNNER_PATH), RG_MARKER, "rg wrapper");
}

// Probe Pi's public grep tool factory rather than guessing lookup behavior.
// The generated rg wrapper exits early with a distinctive stderr message when
// this env var is set, so the probe does not write to disk or enter the tool sandbox.
export async function verifyPiGrepReachesRgWrapper() {
	const previousProbe = process.env.SANDBURG_RG_WRAPPER_PROBE;
	process.env.SANDBURG_RG_WRAPPER_PROBE = ACTIVE_MARKER;
	try {
		await createGrepToolDefinition(AGENT_BIN_DIR).execute(
			"sandburg-rg-wrapper-probe",
			{
				pattern: "sandburg-wrapper-probe-pattern-that-should-not-matter",
				path: TOOL_SANDBOX_RUNNER_PATH,
				literal: true,
				limit: 1,
			},
			undefined,
			undefined,
			undefined,
		);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		if (message.includes(RG_PROBE_MESSAGE)) return;
		fatal(
			[
				"Pi's grep tool invoked rg, but the managed wrapper probe did not respond as expected.",
				"",
				`  wrapper: ${RG_WRAPPER_PATH}`,
				`  error: ${message}`,
			].join("\n"),
		);
	} finally {
		if (previousProbe === undefined) delete process.env.SANDBURG_RG_WRAPPER_PROBE;
		else process.env.SANDBURG_RG_WRAPPER_PROBE = previousProbe;
	}

	fatal(
		[
			"Pi's grep tool did not invoke the managed rg wrapper:",
			"",
			`  ${RG_WRAPPER_PATH}`,
			"",
			"The bash tool would be sandboxed, but grep would bypass the tool sandbox.",
		].join("\n"),
	);
}
