// Sandburg helper installers and shell wrapper generation
import { createGrepToolDefinition, getAgentDir } from "@mariozechner/pi-coding-agent";
import { spawnSync } from "child_process";
import {
	accessSync,
	chmodSync,
	closeSync,
	constants,
	existsSync,
	mkdirSync,
	openSync,
	readFileSync,
	readSync,
	realpathSync,
	renameSync,
	rmSync,
	statSync,
	writeFileSync,
} from "fs";
import { basename, dirname, isAbsolute, join, resolve } from "path";

export const ACTIVE_MARKER = "sandburg-extension-v1";
const RG_PROBE_MESSAGE = "sandburg-rg-wrapper-probe-hit";
export const TOOL_SANDBOX_RUNNER_MARKER = "# sandburg-extension-managed: tool-sandbox-runner";
export const RG_MARKER = "# sandburg-extension-managed: rg-wrapper";
export const AGENT_DIR = resolve(getAgentDir());
export const AGENT_BIN_DIR = join(AGENT_DIR, "bin");
export const AUTH_JSON_PATH = join(AGENT_DIR, "auth.json");
export const TOOL_SANDBOX_RUNNER_PATH = join(AGENT_BIN_DIR, "sandburg-tool-sandbox");
export const RG_WRAPPER_PATH = join(AGENT_BIN_DIR, "rg");
export const JITI_CACHE_DIR = "/tmp/jiti";
const extraRoPathsValue = process.env.SANDBURG_RO_PATHS ?? "";
export const EXTRA_RO_PATHS = extraRoPathsValue === "" ? [] : extraRoPathsValue.split(":");

type ManagedExecutableSpec = {
	label: string;
	path: string;
	marker: string;
	content: string;
};

const TOOL_SANDBOX_RUNNER_SCRIPT = `#!/usr/bin/env bash
${TOOL_SANDBOX_RUNNER_MARKER}
#
# Generated by the Sandburg Pi extension. Safe to remove when Pi is not using it;
# the extension recreates it on startup. Do not edit in place: if customization is
# needed, change the extension that generated this file.

set -euo pipefail

if (($# == 0)); then
    echo "Usage: sandburg-tool-sandbox COMMAND [ARG...]" >&2
    exit 2
fi

: "\${SANDBURG_ACTIVE:?sandburg-tool-sandbox: SANDBURG_ACTIVE is not set}"
: "\${SANDBURG_AGENT_DIR:?sandburg-tool-sandbox: SANDBURG_AGENT_DIR is not set}"
: "\${SANDBURG_AUTH_PATH:?sandburg-tool-sandbox: SANDBURG_AUTH_PATH is not set}"

agent_dir=$SANDBURG_AGENT_DIR
auth_path=$SANDBURG_AUTH_PATH
extra_ro_paths=\${SANDBURG_RO_PATHS:-}
pass_vars=\${SANDBURG_PASS_VARS:-}

if [[ ! -d $agent_dir ]]; then
    echo "sandburg-tool-sandbox: Pi agent directory not found: $agent_dir" >&2
    exit 2
fi

bwrap_args=(
    --unshare-all
    --die-with-parent
    --new-session
    --bind / /
    --dev /dev
    --proc /proc
    --ro-bind "$agent_dir" "$agent_dir"
)

# Extra read-only paths are supplied by trusted launch configuration as a
# colon-separated list. Each path is rebound read-only so agent-facing
# subprocesses cannot mutate protected Pi state through explicit backing-store
# aliases. bwrap fails closed if a configured path is missing; invalid entries
# are rejected by the extension’s setup check before agent tools run.
IFS=: read -r -a extra_ro_path_array <<< "$extra_ro_paths"
for path in "\${extra_ro_path_array[@]}"; do
    bwrap_args+=(--ro-bind "$path" "$path")
done

env_args=(--clearenv)
declare -A passed_env_names=()

env_is_exported() {
    local declaration
    declaration=$(declare -p "$1" 2>/dev/null) || return 1
    case $declaration in
        declare\\ -*x*) return 0 ;;
        *) return 1 ;;
    esac
}

pass_env_if_set() {
    local name=$1
    [[ -z \${passed_env_names[$name]+x} ]] || return 0
    passed_env_names[$name]=1
    if env_is_exported "$name"; then
        env_args+=(--setenv "$name" "\${!name}")
    fi
}

pass_configured_var() {
    local name=$1

    if [[ -z $name ]]; then
        echo "sandburg-tool-sandbox: empty variable name in SANDBURG_PASS_VARS" >&2
        exit 2
    fi

    if [[ ! $name =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
        echo "sandburg-tool-sandbox: invalid variable name in SANDBURG_PASS_VARS: $name" >&2
        exit 2
    fi

    case $name in
        SANDBURG_*)
            echo "sandburg-tool-sandbox: reserved variable name in SANDBURG_PASS_VARS: $name" >&2
            exit 2
            ;;
    esac

    pass_env_if_set "$name"
}

for name in HOME USER LOGNAME SHELL PATH TERM LANG COLORTERM; do
    pass_env_if_set "$name"
done

for name in "\${!LC_@}"; do
    pass_env_if_set "$name"
done

# Trusted launch configuration may pass additional exact-name environment
# variables. Missing listed variables are omitted, like missing default
# variables above.
if [[ -n $pass_vars ]]; then
    if [[ $pass_vars == :* || $pass_vars == *: || $pass_vars == *::* ]]; then
        echo "sandburg-tool-sandbox: empty variable name in SANDBURG_PASS_VARS" >&2
        exit 2
    fi

    IFS=: read -r -a pass_vars_array <<< "$pass_vars"
    for name in "\${pass_vars_array[@]}"; do
        pass_configured_var "$name"
    done
fi

env_args+=(
    --setenv SANDBURG_ACTIVE "$SANDBURG_ACTIVE"
    --setenv SANDBURG_TOOL_SANDBOX 1
    --setenv SANDBURG_AGENT_DIR "$agent_dir"
    --setenv SANDBURG_AUTH_PATH "$auth_path"
)

if [[ -n $extra_ro_paths ]]; then
    env_args+=(--setenv SANDBURG_RO_PATHS "$extra_ro_paths")
fi

# Mount an empty regular file over auth.json. --ro-bind-data takes an fd, so fd
# 9 is opened from /dev/null at the end of this command.
exec bwrap \
    "\${bwrap_args[@]}" \
    --ro-bind-data 9 "$auth_path" \
    --tmpfs /tmp/jiti \
    "\${env_args[@]}" \
    "$@" 9</dev/null
`;

export function shQuote(value: string): string {
	return `'${value.replace(/'/g, `'\\''`)}'`;
}

function rgWrapperScript(realRgPath: string, toolSandboxRunnerPath: string): string {
	return `#!/bin/sh
${RG_MARKER}
#
# Generated by the Sandburg Pi extension. Safe to remove when Pi is not using it;
# the extension recreates it on startup. Do not edit in place: if customization is
# needed, change the extension that generated this file.

set -eu

active_marker=${shQuote(ACTIVE_MARKER)}
probe_message=${shQuote(RG_PROBE_MESSAGE)}
real_rg=${shQuote(realRgPath)}
tool_sandbox_runner=${shQuote(toolSandboxRunnerPath)}

# Startup self-test hook used by the extension to verify that Pi’s grep tool
# reaches this wrapper. This intentionally writes only to stderr and exits
# before entering the sandbox or touching the filesystem.
if [ "\${SANDBURG_RG_WRAPPER_PROBE:-}" = "$active_marker" ]; then
    echo "$probe_message" >&2
    exit 86
fi

if [ "\${SANDBURG_ACTIVE:-}" != "$active_marker" ] || [ "\${SANDBURG_TOOL_SANDBOX:-}" = 1 ]; then
    exec "$real_rg" "$@"
fi

exec "$tool_sandbox_runner" "$real_rg" "$@"
`;
}

function errorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

function isExecutable(path: string): boolean {
	try {
		accessSync(path, constants.X_OK);
		return true;
	} catch {
		return false;
	}
}

function isScriptFile(path: string): boolean {
	let fd: number | undefined;

	try {
		fd = openSync(realpathSync(path), "r");
		const bytes = Buffer.allocUnsafe(2);
		const bytesRead = readSync(fd, bytes, 0, bytes.length, 0);
		return bytesRead === 2 && bytes[0] === 0x23 && bytes[1] === 0x21;
	} catch {
		return false;
	} finally {
		if (fd !== undefined) {
			try {
				closeSync(fd);
			} catch {
				// Ignore close errors in this best-effort file probe.
			}
		}
	}
}

function isRipgrep(path: string): boolean {
	if (!isExecutable(path)) return false;
	const result = spawnSync(path, ["--version"], {
		encoding: "utf-8",
		stdio: ["ignore", "pipe", "ignore"],
		timeout: 3000,
	});
	return result.status === 0 && result.stdout.startsWith("ripgrep ");
}

function isPlainRipgrep(path: string): boolean {
	return !isScriptFile(path) && isRipgrep(path);
}

function writeExecutable(path: string, content: string) {
	const tempPath = join(dirname(path), `.${basename(path)}.${process.pid}.${Date.now()}.${Math.random().toString(36).slice(2)}.tmp`);
	try {
		writeFileSync(tempPath, content, { encoding: "utf-8", mode: 0o755, flag: "wx" });
		chmodSync(tempPath, 0o755);
		renameSync(tempPath, path);
	} catch (error) {
		rmSync(tempPath, { force: true });
		throw error;
	}
}

function ensureExecutable(path: string, label: string): string[] {
	if (isExecutable(path)) return [];

	try {
		chmodSync(path, statSync(path).mode | 0o100);
	} catch (error) {
		return [`${label}: cannot make executable: ${path}: ${errorMessage(error)}`];
	}

	return isExecutable(path) ? [] : [`${label}: is not executable: ${path}`];
}

function readExistingManagedExecutable(spec: ManagedExecutableSpec): { content?: string; violations: string[] } {
	if (!existsSync(spec.path)) return { violations: [] };

	let content: string;
	try {
		content = readFileSync(spec.path, "utf-8");
	} catch (error) {
		return { violations: [`${spec.label}: cannot read: ${spec.path}: ${errorMessage(error)}`] };
	}

	if (!content.includes(spec.marker)) {
		return { violations: [`${spec.label}: unmanaged file at ${spec.path}`] };
	}

	return { content, violations: [] };
}

function installManagedExecutable(spec: ManagedExecutableSpec): string[] {
	const existing = readExistingManagedExecutable(spec);
	if (existing.violations.length > 0) return existing.violations;

	if (existing.content !== spec.content) {
		try {
			writeExecutable(spec.path, spec.content);
		} catch (error) {
			return [`${spec.label}: cannot install: ${spec.path}: ${errorMessage(error)}`];
		}
	}

	return ensureExecutable(spec.path, spec.label);
}

function checkManagedExecutable(spec: ManagedExecutableSpec): string[] {
	if (!existsSync(spec.path)) return [`${spec.label}: missing: ${spec.path}`];

	const existing = readExistingManagedExecutable(spec);
	if (existing.violations.length > 0) return existing.violations;

	const violations: string[] = [];
	if (existing.content !== spec.content) {
		violations.push(`${spec.label}: contents differ from this extension's expected helper: ${spec.path}`);
	}
	if (!isExecutable(spec.path)) {
		violations.push(`${spec.label}: not executable: ${spec.path}`);
	}
	return violations;
}

function pathEntries(pathValue: string): string[] {
	return pathValue.split(":").filter(Boolean);
}

function sameExistingPath(a: string, b: string): boolean {
	try {
		return realpathSync(a) === realpathSync(b);
	} catch {
		return resolve(a) === resolve(b);
	}
}

function findRealRgOnPathSkipping(binDir: string): string | undefined {
	for (const dir of pathEntries(process.env.PATH ?? "")) {
		if (!isAbsolute(dir)) continue;
		const candidateDir = resolve(dir);
		if (sameExistingPath(candidateDir, binDir)) continue;

		const candidate = join(candidateDir, "rg");
		if (existsSync(candidate) && isPlainRipgrep(candidate)) {
			return realpathSync(candidate);
		}
	}
	return undefined;
}

const NO_REAL_RG_VIOLATION = `rg wrapper: no real ripgrep binary found outside ${AGENT_BIN_DIR}; install ripgrep or adjust PATH, then /reload.`;

// Resolve the real ripgrep that the persistent wrapper will delegate to. PATH
// fallback deliberately skips getAgentDir()/bin and relative entries so the
// wrapper cannot delegate to itself.
function resolveRealRg(): string | undefined {
	return findRealRgOnPathSkipping(AGENT_BIN_DIR);
}

function getManagedHelperSpecs(): { specs: ManagedExecutableSpec[]; violations: string[] } {
	const specs: ManagedExecutableSpec[] = [
		{
			label: "tool sandbox runner",
			path: TOOL_SANDBOX_RUNNER_PATH,
			marker: TOOL_SANDBOX_RUNNER_MARKER,
			content: TOOL_SANDBOX_RUNNER_SCRIPT,
		},
	];

	const realRg = resolveRealRg();
	if (!realRg) return { specs, violations: [NO_REAL_RG_VIOLATION] };

	specs.push({
		label: "rg wrapper",
		path: RG_WRAPPER_PATH,
		marker: RG_MARKER,
		content: rgWrapperScript(realRg, TOOL_SANDBOX_RUNNER_PATH),
	});
	return { specs, violations: [] };
}

export function installSandburgHelpers(): string[] {
	try {
		mkdirSync(AGENT_BIN_DIR, { recursive: true });
	} catch (error) {
		return [`agent bin directory: cannot create ${AGENT_BIN_DIR}: ${errorMessage(error)}`];
	}

	const { specs, violations } = getManagedHelperSpecs();
	if (violations.length > 0) return violations;

	for (const spec of specs) {
		const specViolations = installManagedExecutable(spec);
		if (specViolations.length > 0) return specViolations;
	}
	return [];
}

export function checkSandburgHelpers(): string[] {
	const { specs, violations } = getManagedHelperSpecs();
	return [...violations, ...specs.flatMap((spec) => checkManagedExecutable(spec))];
}

// Probe Pi's public grep tool factory rather than guessing lookup behavior.
// The generated rg wrapper exits early with a distinctive stderr message when
// this env var is set, so the probe does not write to disk or enter the tool sandbox.
export async function verifyPiGrepReachesRgWrapper(): Promise<string[]> {
	const previousProbe = process.env.SANDBURG_RG_WRAPPER_PROBE;
	process.env.SANDBURG_RG_WRAPPER_PROBE = ACTIVE_MARKER;
	try {
		await createGrepToolDefinition(AGENT_BIN_DIR).execute(
			"sandburg-rg-wrapper-probe",
			{
				pattern: "sandburg-wrapper-probe-pattern-that-should-not-matter",
				path: TOOL_SANDBOX_RUNNER_PATH,
				literal: true,
				limit: 1,
			},
			undefined,
			undefined,
			undefined,
		);
	} catch (error) {
		const message = errorMessage(error);
		if (message.includes(RG_PROBE_MESSAGE)) return [];
		return [
			`Pi's grep tool invoked rg, but the managed wrapper probe did not respond as expected; wrapper: ${RG_WRAPPER_PATH}; error: ${message}`,
		];
	} finally {
		if (previousProbe === undefined) delete process.env.SANDBURG_RG_WRAPPER_PROBE;
		else process.env.SANDBURG_RG_WRAPPER_PROBE = previousProbe;
	}

	return [
		`Pi's grep tool did not invoke the managed rg wrapper: ${RG_WRAPPER_PATH}; bash would be sandboxed, but grep would bypass the tool sandbox.`,
	];
}
